---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---

```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges()
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## What's Inside The Tin

A copy of the [Protomolecule Font](https://www.reddit.com/r/TheExpanse/comments/ay322l/protomolecule_font/).

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r lib-ex}
library(ggexpanse)

# current version
packageVersion("ggexpanse")

extrafont::loadfonts(quiet=TRUE)
```

```{r pal1}
scales::show_col(as.character(expanse_cols))
```

```{r pal2}
scales::show_col(expanse_palette)
```

```{r plotex, fig.width=8, fig.height=6}
ggplot() +
  geom_smooth(
    data = mtcars, method = "lm", 
    aes(wt, mpg), colour = "white", 
    fill = "gray60", show.legend = FALSE
  ) +
  geom_point(
    data = mtcars,
    aes(wt, mpg, fill = factor(carb)), 
    shape = 21, color = "gray60", size = 4
  ) +
  scale_colour_expanse() +
  scale_fill_expanse() +
  labs(
    title = "Stars Are Better_Off Without Us",
    subtitle = "Say what you_will about organized_crime, at least it’s organized."
  ) +
  theme_expanse(grid = "XY")
```

## ggexpanse Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```

## Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. By participating in this project you agree to abide by its terms.
